#!/bin/bash -e
set -x
PREREQ=""

prereqs () {
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/awk /bin/
copy_exec /usr/bin/tr /bin/
copy_exec /bin/grep /bin/
copy_exec /bin/bash /bin/
copy_exec /usr/bin/base64 /bin/
copy_exec /bin/sed /bin/
copy_exec /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/
copy_exec /usr/lib/x86_64-linux-gnu/libxml2.so.2 /lib/x86_64-linux-gnu/
copy_exec /usr/bin/xmllint /bin/
copy_exec /usr/bin/basename /bin/
copy_exec /usr/bin/sha1sum /bin/sha1sum
copy_exec /usr/bin/sha256sum /bin/sha256sum
copy_exec `which insmod` /bin/
copy_exec `which findfs` /bin/
copy_exec $TBOOTXM_BIN/tpmextend /bin/
copy_exec $TBOOTXM_LIB/libwml.so /lib/
copy_exec $TBOOTXM_BIN/measure /bin/

exit 0
