/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/intel-secl/intel-secl/v5/pkg/isecl-k8s-extensions/isecl-k8s-controller/crdSchema/api/hostattribute/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostAttributesCrds implements HostAttributesCrdInterface
type FakeHostAttributesCrds struct {
	Fake *FakeCrdV1beta1
	ns   string
}

var hostattributescrdsResource = schema.GroupVersionResource{Group: "crd.isecl.intel.com", Version: "v1beta1", Resource: "hostattributescrds"}

var hostattributescrdsKind = schema.GroupVersionKind{Group: "crd.isecl.intel.com", Version: "v1beta1", Kind: "HostAttributesCrd"}

// Get takes name of the hostAttributesCrd, and returns the corresponding hostAttributesCrd object, and an error if there is any.
func (c *FakeHostAttributesCrds) Get(name string, options v1.GetOptions) (result *v1beta1.HostAttributesCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hostattributescrdsResource, c.ns, name), &v1beta1.HostAttributesCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostAttributesCrd), err
}

// List takes label and field selectors, and returns the list of HostAttributesCrds that match those selectors.
func (c *FakeHostAttributesCrds) List(opts v1.ListOptions) (result *v1beta1.HostAttributesCrdList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hostattributescrdsResource, hostattributescrdsKind, c.ns, opts), &v1beta1.HostAttributesCrdList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.HostAttributesCrdList{ListMeta: obj.(*v1beta1.HostAttributesCrdList).ListMeta}
	for _, item := range obj.(*v1beta1.HostAttributesCrdList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostAttributesCrds.
func (c *FakeHostAttributesCrds) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hostattributescrdsResource, c.ns, opts))

}

// Create takes the representation of a hostAttributesCrd and creates it.  Returns the server's representation of the hostAttributesCrd, and an error, if there is any.
func (c *FakeHostAttributesCrds) Create(hostAttributesCrd *v1beta1.HostAttributesCrd) (result *v1beta1.HostAttributesCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hostattributescrdsResource, c.ns, hostAttributesCrd), &v1beta1.HostAttributesCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostAttributesCrd), err
}

// Update takes the representation of a hostAttributesCrd and updates it. Returns the server's representation of the hostAttributesCrd, and an error, if there is any.
func (c *FakeHostAttributesCrds) Update(hostAttributesCrd *v1beta1.HostAttributesCrd) (result *v1beta1.HostAttributesCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hostattributescrdsResource, c.ns, hostAttributesCrd), &v1beta1.HostAttributesCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostAttributesCrd), err
}

// Delete takes name of the hostAttributesCrd and deletes it. Returns an error if one occurs.
func (c *FakeHostAttributesCrds) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hostattributescrdsResource, c.ns, name), &v1beta1.HostAttributesCrd{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostAttributesCrds) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hostattributescrdsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.HostAttributesCrdList{})
	return err
}

// Patch applies the patch and returns the patched hostAttributesCrd.
func (c *FakeHostAttributesCrds) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.HostAttributesCrd, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hostattributescrdsResource, c.ns, name, pt, data, subresources...), &v1beta1.HostAttributesCrd{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.HostAttributesCrd), err
}
